### PR TITLE
Relax bounds

### PR DESCRIPTION
**Pull request by TeofilC**

### CODE REVIEW

**Comment by TeofilC** [comment]
Friendly ping @hiratara . If you'd be willing to give me permissions, I would be happy to help with bumping version bounds

**Comment by hiratara** [comment]
Hi @TeofilC,

Thank you for your PR and for the reminder. I apologize for not noticing it earlier. In Japan, the end of the year and the New Year period is a major holiday season, so I plan to review this during that time. Please let me know if there is any urgency.

**Comment by TeofilC** [comment]
There's no urgency. Enjoy!

**Comment by hiratara** [comment]
I've reviewed your patch. I realized I need to make some tweaks to the GitHub Actions in this PR, but once that's done, I'll go ahead and release it. Thank you for your contribution!

**Comment by TeofilC** [comment]
Thanks!

**Pull request merged**
